# default config.yml

results-per-page: 10

use-mysql: false

mysql:
  hostname: localhost
  port: 3306
  database: uTest
  username: minecraft
  password: minecraft

manage-applications: false

when-test-approved:
  promote: true
  member-group: members
  broadcast: true
  broadcast-message: Congratulations to <player> for becoming a member!

quiz-settings:
  max-attempts: 3

quiz-questions:
  - Q1
  - Q2
  - Q3
  - Q4